### ISSUE TITLE
server-side processing error 

### ISSUE THREAD

**Issue by ghost** [martinberlin/datatables-dynamic-columns#1]
This is great stuff!

With your code and trying to convert to server-side processing using:

> "columns": data.columns,
> "serverSide": true,

I get an: 

> DataTables warning: table id=databasestable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

The JSON response is empty and I get a 

> TypeError: g is null inside jquery.dataTables.min.js:36:442
	
Any idea?

Thanks!

**Comment by 66eagle** [comment]
how to make page. . and search.  can you update it . with pages and search.

**Comment by martinberlin** [comment]
This won’t work using server side like this since we are “fabricating” the table ourselves.
And I’m not going to update it sorry. This is just an example and it’s open source is your job guys to implement something different.
Paging and search should work. At least does for me.
